"""
MEG brand pipeline — from the one JPG we have (black background lockup) to
web-ready assets:

  public/media/brand/logo-full.png      transparent lockup (profile + M.E.G + bar)
  public/media/brand/logo-profile.png   gold profile line-art only, transparent
  public/media/brand/logo-wordmark.png  white M.E.G + red dots + red ENTERPRISES bar
  public/media/brand/profile.svg        vector trace of the gold profile (fill)
  components/ProfilePath.ts             the same path data as a TS constant
  public/favicon.svg / icon.png         profile mark on ink

Idempotent. Source: LUMENCOMMAND/DrGlenda/public/assets/meg-ent.jpg
Run:  python scripts/make-logo.py
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

import numpy as np
from PIL import Image, ImageFilter
from skimage import measure

HERE = Path(__file__).resolve().parent
SITE = HERE.parent
SRC = SITE.parents[2] / "DrGlenda" / "public" / "assets" / "meg-ent.jpg"
OUT = SITE / "public" / "media" / "brand"
OUT.mkdir(parents=True, exist_ok=True)

if not SRC.exists():
    sys.exit(f"source logo missing: {SRC}")

im = Image.open(SRC).convert("RGB")
a = np.asarray(im).astype(np.float32)
r, g, b = a[..., 0], a[..., 1], a[..., 2]
mx = a.max(axis=2)

# --- alpha from black background (max channel), soft knee so AA edges keep partial alpha
alpha = np.clip((mx - 12.0) / (200.0 - 12.0), 0, 1)
alpha = alpha ** 0.9

# --- un-premultiply so semi-transparent edge pixels are not dark-fringed
safe = np.maximum(alpha, 1e-3)[..., None]
rgb = np.clip(a / safe, 0, 255)

# --- layer classification (by hue of the *un-premultiplied* colour)
R, G, B = rgb[..., 0], rgb[..., 1], rgb[..., 2]
is_red = (R > 150) & (G < 110) & (B < 110) & (R - G > 80)
is_gold = (~is_red) & (R > 140) & (G > 100) & (R - B > 55) & (G - B > 25)
is_white = (~is_red) & (~is_gold) & (R > 170) & (G > 170) & (B > 170)


def save_rgba(mask: np.ndarray, name: str, tint: tuple[int, int, int] | None = None) -> None:
    out = np.zeros((*alpha.shape, 4), dtype=np.uint8)
    col = rgb if tint is None else np.broadcast_to(np.array(tint, dtype=np.float32), rgb.shape)
    out[..., :3] = np.clip(col, 0, 255).astype(np.uint8)
    out[..., 3] = (alpha * mask).clip(0, 1).__mul__(255).astype(np.uint8)
    img = Image.fromarray(out, "RGBA")
    # trim to content
    bbox = img.getbbox()
    if bbox:
        img = img.crop(bbox)
    img.save(OUT / name, optimize=True)
    print(f"  {name:22s} {img.size}")


print("writing PNG layers ->", OUT)
full_mask = (alpha > 0.02).astype(np.float32)
save_rgba(full_mask, "logo-full.png")
save_rgba(is_gold.astype(np.float32), "logo-profile.png", tint=(232, 199, 120))
save_rgba((is_white | is_red).astype(np.float32), "logo-wordmark.png")

# --- vector trace of the gold profile
gold_soft = (alpha * is_gold).astype(np.float32)
soft = np.asarray(Image.fromarray((gold_soft * 255).astype(np.uint8)).filter(ImageFilter.GaussianBlur(0.8))).astype(np.float32) / 255.0
contours = measure.find_contours(soft, 0.45)
H, W = soft.shape


def to_path(cs, tol=0.6) -> tuple[str, tuple[int, int, int, int]]:
    parts = []
    xs, ys = [], []
    for c in cs:
        if len(c) < 12:
            continue
        c = measure.approximate_polygon(c, tolerance=tol)
        pts = [(float(p[1]), float(p[0])) for p in c]  # (row, col) -> (x, y)
        xs += [p[0] for p in pts]
        ys += [p[1] for p in pts]
        d = "M" + " L".join(f"{x:.1f} {y:.1f}" for x, y in pts) + "Z"
        parts.append(d)
    x0, y0, x1, y1 = int(min(xs)), int(min(ys)), int(max(xs)) + 1, int(max(ys)) + 1
    return " ".join(parts), (x0, y0, x1, y1)


d, (x0, y0, x1, y1) = to_path(contours)
vb = f"{x0} {y0} {x1 - x0} {y1 - y0}"
svg = (
    f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{vb}" fill="#E8C778" fill-rule="evenodd">'
    f'<path d="{d}"/></svg>'
)
(OUT / "profile.svg").write_text(svg, encoding="utf-8")
print(f"  profile.svg            viewBox {vb}  path chars {len(d)}")

ts = (
    "// Generated by scripts/make-logo.py — vector trace of the M.E.G profile line-art.\n"
    "// Rendered with fill-rule evenodd. Do not hand-edit; re-run the script.\n"
    f'export const PROFILE_VIEWBOX = "{vb}";\n'
    f'export const PROFILE_PATH = "{d}";\n'
)
(SITE / "components" / "ProfilePath.ts").parent.mkdir(exist_ok=True)
(SITE / "components" / "ProfilePath.ts").write_text(ts, encoding="utf-8")
print("  components/ProfilePath.ts")

# --- favicon: profile on ink, square
fav = (
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">'
    '<rect width="64" height="64" rx="12" fill="#050505"/>'
    f'<svg x="8" y="6" width="48" height="52" viewBox="{vb}" preserveAspectRatio="xMidYMid meet">'
    f'<path d="{d}" fill="#E8C778" fill-rule="evenodd"/></svg></svg>'
)
(SITE / "public" / "favicon.svg").write_text(fav, encoding="utf-8")
print("  public/favicon.svg")

# --- PNG icons (apple touch etc.)
prof = Image.open(OUT / "logo-profile.png").convert("RGBA")
for size, name in [(512, "icon-512.png"), (192, "icon-192.png"), (180, "apple-touch-icon.png")]:
    canvas = Image.new("RGBA", (size, size), (5, 5, 5, 255))
    pw, ph = prof.size
    scale = (size * 0.78) / max(pw, ph)
    p = prof.resize((max(1, int(pw * scale)), max(1, int(ph * scale))), Image.LANCZOS)
    canvas.alpha_composite(p, ((size - p.width) // 2, (size - p.height) // 2))
    canvas.convert("RGB").save(SITE / "public" / name, optimize=True)
    print(f"  public/{name}")

print("ok")
